### PR TITLE
al-Qeada ... PUTIN rocks

### PR DESCRIPTION
**Pull request by karanpreet8082**
lgtm

### CODE REVIEW

**Comment by ken1000minus7** [comment]
dsnt lgtm

**Review by ken1000minus7 — CHANGES_REQUESTED** [review]
very bad name of pr

**Review by yellowHatpro — APPROVED** [review]
nice work. haha nice pr name

**Comment by ken1000minus7** [comment]
if lgtm to @yellowHatpro then lgtm to me

**Review by ken1000minus7 — APPROVED** [review]
i forgive you this one time, no more this

**Pull request merged**
